### ISSUE TITLE
参考9.17号的打包建议,新克隆打包依然报错

### ISSUE THREAD

**Issue by xiaoyuxia8** [zhuyihe/vue-admin-project#3]
麻烦看到消息帮忙参考下,万分感激

**Comment by xiaoyuxia8** [comment]
已经解决了,使用vue ui进行检测,使用build打包,在/ 前面加个小点就成功了

**Comment by zhuyihe** [comment]
ok，不好意思，前几天没看到问题，不过谢谢你，解决了就好

**Comment by zhuyihe** [comment]
> 已经解决了,使用vue ui进行检测,使用build打包,在/ 前面加个小点就成功了

ok，不好意思，前几天没看到问题，解决了就好，有问题随时issues
